name: Deploy Landing

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t torment93/randompicks-landing:latest .

      - name: Push image
        run: docker push torment93/randompicks-landing:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 <<EOF
${{ secrets.SSH_PRIVATE_KEY }}
EOF
          chmod 600 ~/.ssh/id_ed25519

      - name: Debug SSH file
        run: |
          echo "LINES:"
          wc -l ~/.ssh/id_ed25519
          echo "FIRST:"
          head -n 1 ~/.ssh/id_ed25519
          echo "LAST:"
          tail -n 1 ~/.ssh/id_ed25519
          echo "CONTENT:"
          cat ~/.ssh/id_ed25519

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "kubectl rollout restart deployment/landing -n randompicks && kubectl rollout status deployment/landing -n randompicks"